### PR TITLE
Prep for npm release.

### LINKED ISSUE #4: Need new/latest version on NPM
This latest commit https://github.com/urbit/argon2-wasm/commit/e1df50415ba651125508a9368766c467c22884eb needs to be pushed on to NPM. Not sure who has the creds/skills to do this.

cc @jtobin @joemfb @c-johnson ?

### PR DESCRIPTION
**Pull request by jtobin**
(Resolves #4)

If this is acceptable then I can publish it to npm and swap it into keygen-js.  I decremented the version to 0.9.0 (not strictly necessary, but probably desirable for now), added the submodule requirements to build, and added a prepublish hook to package.json, basically.

* Version: 1.4.0 -> 0.9.0
* Add submodule steps to build.sh
* Update README, add prepublish step to package.json

### CODE REVIEW

**Review by Fang- — APPROVED** [review]
Looks good as far as I can tell. Not sure how I feel about the version number lowering. If anything this should be `1.5.0`, because there have been changes on top of the thing we originally forked this from.

Might also want input from @gavinpatkinson here but I think we're good.

**Comment by jtobin** [comment]
Yeah my thoughts re: the version number -- AFAIK we're the only ones depending on this at the moment, and I'm not confident that we want to publicly commit to the stability that 1.x.x implies yet (nor do I see the need to, since, again, we're the only ones depending on it at the moment).  Per semver, anything less than 1.0.0 implies "anything can change at any time for any reason," which seems desirable here.

Re: the changes since forking from argon2-browser, yeah, forking/renaming the library to 'argon2-wasm' is the only reason I'm comfortable with decrementing the version number at all. 😄

**Comment by Fang-** [comment]
Fair enough. (:

**Comment by jtobin** [comment]
K, I'll publish this bad boy.

**Pull request merged**
